apiVersion: v1
kind: Service
metadata:
  name: nginx-html-service
spec:
  type: NodePort
  selector:
    app: nginx-html
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036
